<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="AR-IT26304" failures="2" tests="7" name="Lenio Challenge" time="29.546" errors="0" timestamp="2022-04-01T10:05:10 ART">
  <testcase classname="tests.LoginTest" name="testCorrectLoginCredentials" time="0.727"/>
  <testcase classname="tests.LoginTest" name="testIncorrectLoginCredentials" time="0.468"/>
  <testcase classname="tests.CheckoutTest" name="testCheckout" time="1.994"/>
  <testcase classname="tests.CheckoutTest" name="testCheckoutFail" time="1.117">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Finish] but found [CHECKOUT: COMPLETE!]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Finish] but found [CHECKOUT: COMPLETE!]
at tests.CheckoutTest.testCheckoutFail(CheckoutTest.java:42)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testCheckoutFail -->
  <testcase classname="backend.tests.CategoriaTest" name="testCategoriaEndpoint" time="7.771"/>
  <testcase classname="backend.tests.CategoriaTest" name="testLocalidades" time="1.273">
    <failure type="java.lang.AssertionError" message="expected [27] but found [28]">
      <![CDATA[java.lang.AssertionError: expected [27] but found [28]
at backend.tests.CategoriaTest.testLocalidades(CategoriaTest.java:56)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testLocalidades -->
  <testcase classname="backend.tests.CategoriaTest" name="testPedidos" time="2.423"/>
</testsuite> <!-- Lenio Challenge -->
